#
# Travis CI recipe to build, test and push docker images to the Docker Hub.
#

sudo: required

language: generic

services:
  - docker

env:
  global:
  - DOCKER_REPO=jlesage/baseimage
  matrix:
  - DOCKER_IMAGE_ARCH=amd64    DOCKER_IMAGE_TAG_PREFIX=alpine-3.6       DOCKERFILE=Dockerfile.alpine       BASEIMAGE=alpine:3.6
  - DOCKER_IMAGE_ARCH=amd64    DOCKER_IMAGE_TAG_PREFIX=alpine-3.7       DOCKERFILE=Dockerfile.alpine       BASEIMAGE=alpine:3.7
  - DOCKER_IMAGE_ARCH=amd64    DOCKER_IMAGE_TAG_PREFIX=alpine-3.8       DOCKERFILE=Dockerfile.alpine       BASEIMAGE=alpine:3.8
  - DOCKER_IMAGE_ARCH=amd64    DOCKER_IMAGE_TAG_PREFIX=alpine-3.6-glibc DOCKERFILE=Dockerfile.alpine-glibc BASEIMAGE=alpine:3.6
  - DOCKER_IMAGE_ARCH=amd64    DOCKER_IMAGE_TAG_PREFIX=alpine-3.7-glibc DOCKERFILE=Dockerfile.alpine-glibc BASEIMAGE=alpine:3.7
  - DOCKER_IMAGE_ARCH=amd64    DOCKER_IMAGE_TAG_PREFIX=alpine-3.8-glibc DOCKERFILE=Dockerfile.alpine-glibc BASEIMAGE=alpine:3.8
  - DOCKER_IMAGE_ARCH=amd64    DOCKER_IMAGE_TAG_PREFIX=debian-8         DOCKERFILE=Dockerfile.debian       BASEIMAGE=debian:jessie-slim
  - DOCKER_IMAGE_ARCH=amd64    DOCKER_IMAGE_TAG_PREFIX=debian-9         DOCKERFILE=Dockerfile.debian       BASEIMAGE=debian:stretch-slim
  - DOCKER_IMAGE_ARCH=amd64    DOCKER_IMAGE_TAG_PREFIX=ubuntu-16.04     DOCKERFILE=Dockerfile.debian       BASEIMAGE=ubuntu:xenial
  - DOCKER_IMAGE_ARCH=amd64    DOCKER_IMAGE_TAG_PREFIX=ubuntu-18.04     DOCKERFILE=Dockerfile.debian       BASEIMAGE=ubuntu:bionic
  - DOCKER_IMAGE_ARCH=i386     DOCKER_IMAGE_TAG_PREFIX=alpine-3.6       DOCKERFILE=Dockerfile.alpine       BASEIMAGE=i386/alpine:3.6
  - DOCKER_IMAGE_ARCH=i386     DOCKER_IMAGE_TAG_PREFIX=alpine-3.7       DOCKERFILE=Dockerfile.alpine       BASEIMAGE=i386/alpine:3.7
  - DOCKER_IMAGE_ARCH=i386     DOCKER_IMAGE_TAG_PREFIX=alpine-3.8       DOCKERFILE=Dockerfile.alpine       BASEIMAGE=i386/alpine:3.8
  - DOCKER_IMAGE_ARCH=i386     DOCKER_IMAGE_TAG_PREFIX=alpine-3.6-glibc DOCKERFILE=Dockerfile.alpine-glibc BASEIMAGE=i386/alpine:3.6
  - DOCKER_IMAGE_ARCH=i386     DOCKER_IMAGE_TAG_PREFIX=alpine-3.7-glibc DOCKERFILE=Dockerfile.alpine-glibc BASEIMAGE=i386/alpine:3.7
  - DOCKER_IMAGE_ARCH=i386     DOCKER_IMAGE_TAG_PREFIX=alpine-3.8-glibc DOCKERFILE=Dockerfile.alpine-glibc BASEIMAGE=i386/alpine:3.8
  - DOCKER_IMAGE_ARCH=i386     DOCKER_IMAGE_TAG_PREFIX=debian-8         DOCKERFILE=Dockerfile.debian       BASEIMAGE=i386/debian:jessie-slim
  - DOCKER_IMAGE_ARCH=i386     DOCKER_IMAGE_TAG_PREFIX=debian-9         DOCKERFILE=Dockerfile.debian       BASEIMAGE=i386/debian:stretch-slim
  - DOCKER_IMAGE_ARCH=i386     DOCKER_IMAGE_TAG_PREFIX=ubuntu-16.04     DOCKERFILE=Dockerfile.debian       BASEIMAGE=i386/ubuntu:xenial
  - DOCKER_IMAGE_ARCH=i386     DOCKER_IMAGE_TAG_PREFIX=ubuntu-18.04     DOCKERFILE=Dockerfile.debian       BASEIMAGE=i386/ubuntu:bionic

before_install:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get -qq update
  - sudo apt-get install -y bats
  - sudo apt-get install -y python3-yaml

script:
  - |
    scripts/build.sh --register-binfmt "$TRAVIS_JOB_ID" "$DOCKER_IMAGE_ARCH" "$BASEIMAGE" "$DOCKERFILE" "$TRAVIS_BRANCH" && \
    scripts/test.sh "$TRAVIS_JOB_ID" "$DOCKER_IMAGE_ARCH"

deploy:
  provider: script
  script: scripts/push.sh --dry-run "$TRAVIS_JOB_ID" "$DOCKER_REPO" "$DOCKER_IMAGE_TAG_PREFIX" "$DOCKER_IMAGE_ARCH" "$TRAVIS_TAG"
  on:
    all_branches: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)[0-9]*)?$

jobs:
  include:
    - stage: MicroBadger Webhook
      if: tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)[0-9]*)?$
      script: scripts/microbadger.sh --dry-run "$MICROBADGER_HOOK"
    - stage: Docker Hub README Update
      if: tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
      script: scripts/readmetodockerhub.sh --dry-run README.md "$DOCKER_REPO" "$DOCKERHUB_USERNAME" "$DOCKERHUB_PASSWORD"
